version: '3'
services:
    database:
        image: mongo
        container_name: mongodb-bitcore
        ports:
        - 27018:27017 # Expose 27018 for access from host, otherwise remove
        # volumes:
        #   - ../data:/data/db
        command: mongod
        restart: always
    
    bitcore-strax-node:
        build:
            context: ../
            dockerfile: Docker/Dockerfile
        container_name: bitcore-strax
        links:
        - database
        ports:
        - 4000:3000
        volumes:
        - ./config:/config
        environment:
            - DB_HOST=database
            - DB_PORT=27017
            - BITCORE_CONFIG_PATH=/config/bitcore.config.json
        restart: always